language: java

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.6.0.deb && sudo service elasticsearch restart

services:
  - elasticsearch

before_script:
  - sleep 10

branches:
  only:
  - master
  - develop
